# Generated by Django 4.2.5 on 2023-10-26 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Likes_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
