# Generated by Django 4.2.5 on 2023-10-30 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_new_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_post',
            name='likes',
        ),
        migrations.CreateModel(
            name='LikesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postLiked', to='network.new_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserLike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
