# Generated by Django 4.2.5 on 2023-10-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_new_post_likes_likesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='likesmodel',
            name='Views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
