# Generated by Django 4.2.5 on 2023-10-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_new_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_post',
            name='likes',
        ),
    ]
