# Generated by Django 4.2.5 on 2023-10-31 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_new_post_likest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_post',
            name='likest',
        ),
        migrations.AddField(
            model_name='likesmodel',
            name='likest',
            field=models.ManyToManyField(default=None, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
