# Generated by Django 4.2.5 on 2023-10-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_new_post_likest_likesmodel_likest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likesmodel',
            name='likest',
        ),
    ]
