# Generated by Django 4.2.5 on 2023-10-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_likesmodel_likest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_post',
            name='date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
